name: 'Auto Clocking'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '30 21 * * *'

jobs:
  Auto Clocking:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
    - name: 'Auto Clocking'
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: main.py
